name: Build and Deploy Documentation
description: |
  Build documentation using breathing cat and deploy to GitHub Pages.

inputs:
  container:
    description: "Name of the Apptainer image."
    type: str
    default: container.sif
  build_dir:
    description: "Directory to which build files are written."
    type: str
    default: "docbuild"

outputs:
  page_url:
    description: "URL to the deployed documentation."
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Build documentation
      shell: bash
      run: |
        pkg_name=${GITHUB_REPOSITORY#*/}
        . install/setup.bash
        python_dir=$(python3 -c "import importlib, os; print(os.path.dirname(importlib.util.find_spec('${pkg_name}').origin))")
        apptainer run ${{ inputs.container }} bcat -o "${{ inputs.build_dir }}" -p . --python-dir "${python_dir}"

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ inputs.build_dir }}/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
